### PR TITLE
Rinchi chain of commits

### PR DESCRIPTION
**Pull request by uli-f**

### CODE REVIEW

**Comment by kerberizer** [comment]
@uli-f Thank you very much for the pull request! Could you please rebase it to the `rinchi` branch, because ecc481072e69b897f267cdff88dafa27783164a4 is already merged there as 896fbf48e866f8417f7b5bb6b8a78da8b4e3df23 and so it's superfluous here. It would be really nice to do the same with #10 too.

**Comment by uli-f** [comment]
> @uli-f Thank you very much for the pull request! Could you please rebase it to the `rinchi` branch, because [ecc4810](https://github.com/ideaconsult/jna-inchi/commit/ecc481072e69b897f267cdff88dafa27783164a4) is already merged there as [896fbf4](https://github.com/ideaconsult/jna-inchi/commit/896fbf48e866f8417f7b5bb6b8a78da8b4e3df23) and so it's superfluous here

@kerberizer Done.

**Comment by uli-f** [comment]
> It would be really nice to do the same with #10 too.

Please see #10 for any follow up messages regarding this.

**Comment by kerberizer** [comment]
Interactively rebased and merged (more in https://github.com/ideaconsult/jna-inchi/pull/10#issuecomment-1274754379).

**Pull request closed without merging**
